# SPDX-License-Identifier: Apache-2.0
# AWS resource operations. Source after scripts/_lib.sh for log, die, and confirm.
# Callers supply the deployment settings used by each operation.

# Pin a CRD version compatible with the rendered SparkApplication fields.
# spark.jobNamespaces controls which namespaces the operator watches.
SPARK_OPERATOR_VERSION="${SPARK_OPERATOR_VERSION:-2.5.2}"
SPARK_OPERATOR_RELEASE=spark-operator
SPARK_OPERATOR_NAMESPACE=spark-operator
SPARK_OPERATOR_REPO=https://kubeflow.github.io/spark-operator

# Missing tags may be an API error or an empty list; both mean unowned here.
bucket_is_ours() {
	local tags
	tags="$(aws s3api get-bucket-tagging --bucket "$1" \
		--query "TagSet[?Key=='$TAG_KEY'].Value" --output text 2>/dev/null)" || return 1
	[[ $tags == true ]]
}

# Only configure existing buckets carrying the benchmark tag. Tag replacement
# and versioning changes could otherwise alter an unrelated bucket.
create_bucket() {
	if aws s3api head-bucket --bucket "$BUCKET" >/dev/null 2>&1; then
		bucket_is_ours "$BUCKET" ||
			die "s3://$BUCKET already exists, but its $TAG_KEY=true tag could not be verified.
     Refusing to change its tags or versioning. Set BUCKET to a new bucket name,
     or verify access and tag this bucket $TAG_KEY=true if it is dedicated to the benchmark."
		log "s3://$BUCKET exists"
	else
		log "creating s3://$BUCKET"
		# CreateBucket in us-east-1 rejects an explicit LocationConstraint.
		if [[ $AWS_REGION == us-east-1 ]]; then
			aws s3api create-bucket --bucket "$BUCKET" >/dev/null
		else
			aws s3api create-bucket --bucket "$BUCKET" \
				--create-bucket-configuration "LocationConstraint=$AWS_REGION" >/dev/null
		fi
	fi
	aws s3api put-public-access-block --bucket "$BUCKET" \
		--public-access-block-configuration \
		BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
	aws s3api put-bucket-tagging --bucket "$BUCKET" --tagging "TagSet=[{Key=$TAG_KEY,Value=true}]"
	# Suspend enabled versioning to avoid retaining billable deleted corpus data.
	if [[ "$(aws s3api get-bucket-versioning --bucket "$BUCKET" --query 'Status' --output text)" == Enabled ]]; then
		log "suspending versioning on s3://$BUCKET"
		aws s3api put-bucket-versioning --bucket "$BUCKET" --versioning-configuration Status=Suspended
	fi
}

# Grow broker storage to MSK_VOLUME_GIB when needed; MSK cannot shrink it.
# Enough storage prevents broker capacity from limiting the offered rate.
grow_broker_volume() {
	local reported state version current update_error
	# Read size, state, and update version from one response.
	reported="$(aws kafka describe-cluster --cluster-arn "$MSK_ARN" \
		--query 'ClusterInfo.[State,CurrentVersion,BrokerNodeGroupInfo.StorageInfo.EbsStorageInfo.VolumeSize]' \
		--output text)" ||
		die "could not read $MSK_NAME's broker storage; try: aws kafka describe-cluster --cluster-arn $MSK_ARN"
	IFS=$'\t' read -r state version current <<<"$reported"
	# Reject missing numeric fields instead of interpreting AWS CLI's None as zero.
	if [[ -z $current || $current == None ]]; then
		die "$MSK_NAME reports no broker volume size; cannot verify the requested ${MSK_VOLUME_GIB} GiB capacity"
	fi
	if ((current >= MSK_VOLUME_GIB)); then
		log "MSK broker volumes are ${current} GiB, meeting the requested ${MSK_VOLUME_GIB} GiB minimum"
		return 0
	fi
	# An in-progress update may still report the old size; do not request it twice.
	if [[ $state != ACTIVE ]]; then
		log "MSK broker volumes are ${current} GiB and $MSK_NAME is $state; rerun setup after it becomes ACTIVE to verify the requested ${MSK_VOLUME_GIB} GiB capacity"
		return 0
	fi
	log "growing the msk broker volumes from ${current} to ${MSK_VOLUME_GIB} GiB"
	# Use the reported version for the update. The final ACTIVE wait covers it.
	if update_error="$(aws kafka update-broker-storage --cluster-arn "$MSK_ARN" --current-version "$version" \
		--target-broker-ebs-volume-info "KafkaBrokerNodeId=All,VolumeSizeGB=$MSK_VOLUME_GIB" 2>&1)"; then
		return 0
	fi
	case "$update_error" in
	# Cooldowns and concurrent updates are retryable on a later setup invocation.
	*ACTIVE* | *UPDATING* | *ooldown* | *"6 hour"* | *"6-hour"*)
		log "$MSK_NAME cannot increase broker storage to ${MSK_VOLUME_GIB} GiB yet: $update_error"
		;;
	*)
		die "could not grow $MSK_NAME's broker volumes to ${MSK_VOLUME_GIB} GiB: $update_error"
		;;
	esac
}

# Write the selected deployment's site settings. Quote scalars, including the
# numeric-looking Glue warehouse account ID. Leave prices for the operator to fill in.
write_site() {
	local path=$1 parsed read_back=""
	[[ ! -e $path ]] ||
		die "$path already exists; --write-site cannot overwrite it. Choose another path or move the existing file"
	{
		cat <<-SITE
			# Generated by setup.sh --write-site; see docs/run-spec.md for field details.
			corpus_root: "s3://$BUCKET/corpus"
			runs_root: "s3://$BUCKET/runs"
			warehouse: "s3://$BUCKET/warehouse"
		SITE
		if [[ $KAFKA_DEPLOYMENT == external ]]; then
			printf 'kafka: %s\n' "$(yq -o=json -I=0 '.kafka' "$SITE_FILE")"
		else
			cat <<-SITE
				kafka:
				  deployment: $KAFKA_DEPLOYMENT
				  bootstrap_servers: "$BOOTSTRAP"
			SITE
		fi
		if [[ $KAFKA_DEPLOYMENT == managed ]]; then
			cat <<-SITE
				  security:
				    security.protocol: SASL_SSL
				    sasl.mechanism: OAUTHBEARER
				    aws.region: "$AWS_REGION"
			SITE
		elif [[ $KAFKA_DEPLOYMENT == in-cluster ]]; then
			cat <<-SITE
				  security: {}
			SITE
		fi
		if [[ $WITH_SCHEMA_REGISTRY == true && $KAFKA_DEPLOYMENT != external ]]; then
			cat <<-SITE
				  schema_registry:
				    url: "http://schema-registry.$NAMESPACE.svc:8080/apis/ccompat/v7"
			SITE
		fi
		if [[ $KAFKA_DEPLOYMENT == external ]]; then
			printf 'catalog: %s\n' "$(yq -o=json -I=0 '.catalog' "$SITE_FILE")"
		elif [[ $KAFKA_DEPLOYMENT == in-cluster ]]; then
			cat <<-SITE
				catalog:
				  props:
				    uri: "http://lakekeeper.$NAMESPACE.svc:8181/catalog"
				    warehouse: ingest-bench
				    s3.region: "$AWS_REGION"
			SITE
		else
			cat <<-SITE
				catalog:
				  props:
				    uri: "https://glue.$AWS_REGION.amazonaws.com/iceberg"
				    warehouse: "$ACCOUNT"
				    rest.sigv4-enabled: "true"
				    rest.signing-name: glue
				    rest.signing-region: "$AWS_REGION"
				    s3.region: "$AWS_REGION"
			SITE
		fi
		cat <<-SITE
			kubernetes:
			  context: "$KUBE_CONTEXT"
			  namespace: "$NAMESPACE"
			  harness_service_account: "$HARNESS_SERVICE_ACCOUNT"
			  flink_service_account: "$FLINK_SERVICE_ACCOUNT"
			  spark_service_account: "$SPARK_SERVICE_ACCOUNT"
			  service_account_annotations: {}
			  registry: "$ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com"
			  aws_region: "$AWS_REGION"
			  # Optional Secret supplying environment variables for \${env:NAME} references.
			  # secret_name: bench-env
			  node_selector: $NODE_SELECTOR
			  tolerations: $TOLERATIONS
			# Set hourly vCPU and GiB prices using docs/methodology.md's Cost section.
			# Published results cannot use these zero defaults.
			pricing: {vcpu_hour_usd: 0.0, gib_hour_usd: 0.0}
		SITE
	} >"$path"
	# Validate the generated YAML. Remove invalid output so the overwrite guard
	# does not prevent a corrected retry.
	if ! parsed="$(yq -e '.kafka.bootstrap_servers' "$path" 2>&1)"; then
		read_back="yq could not read a site config out of it: $parsed"
	elif [[ $parsed != "$BOOTSTRAP" ]]; then
		read_back="its kafka.bootstrap_servers reads back as '$parsed' rather than '$BOOTSTRAP'"
	fi
	if [[ -n $read_back ]]; then
		rm -f "$path"
		die "removed $path because the generated site configuration failed validation: $read_back"
	fi
	log "wrote $path"
}

# Require the benchmark tag before deleting corpus, run artifacts, and warehouse data.
remove_bucket() {
	if ! aws s3api head-bucket --bucket "$BUCKET" >/dev/null 2>&1; then
		log "s3://$BUCKET is already gone"
		return 0
	fi
	bucket_is_ours "$BUCKET" ||
		die "cannot verify the $TAG_KEY=true tag on s3://$BUCKET: refusing to empty it.
     Check bucket access and BUCKET, or delete the bucket manually"
	printf 'deleting %s permanently removes:\n' "s3://$BUCKET"
	printf '  every corpus generated into it\n'
	printf '  every run%s artifacts, scores and publish logs\n' "'s"
	printf '  the warehouse, and every table any run has written\n'
	if [[ $ASSUME_YES == no ]]; then
		confirm "delete the resources listed above?"
	fi
	log "emptying and deleting s3://$BUCKET"
	aws s3 rm "s3://$BUCKET" --recursive >/dev/null
	local delete_error
	if ! delete_error="$(aws s3api delete-bucket --bucket "$BUCKET" 2>&1)"; then
		case "$delete_error" in
		*BucketNotEmpty*)
			die "s3://$BUCKET still holds objects: $delete_error
     A bucket that was versioned before keeps its noncurrent versions, which \`aws s3 rm\` does not remove.
     Delete them (aws s3api list-object-versions / delete-objects) and re-run with --all."
			;;
		*) die "could not delete s3://$BUCKET: $delete_error" ;;
		esac
	fi
}

choose_kafka_version() {
	local KAFKA_VERSIONS=$1
	# Choose the newest plain ACTIVE 3.x release, excluding tiered variants.
	# Sort a trailing x after numeric patches using a temporary sentinel.
	# Allow no-match through pipefail so the next check can explain the failure.
	MSK_KAFKA_VERSION="$(tr '\t' '\n' <<<"$KAFKA_VERSIONS" |
		grep -E '^3\.[0-9]+\.([0-9]+|x)$' |
		while IFS=. read -r major minor patch; do
			sort_patch=$patch
			[[ $patch == x ]] && sort_patch=999999
			printf '%s %s %s\t%s.%s.%s\n' "$major" "$minor" "$sort_patch" "$major" "$minor" "$patch"
		done |
		sort -k1,1n -k2,2n -k3,3n | tail -1 | cut -f2 || true)"
	[[ -n $MSK_KAFKA_VERSION ]] ||
		die "no ACTIVE 3.x Kafka version among ${KAFKA_VERSIONS//$'\t'/ }; set MSK_KAFKA_VERSION yourself"
}

# A pending Helm operation needs explicit recovery; starting another cannot fix it.
check_operator_release() (
	local release=$1 namespace=$2 status_json status diagnostics
	diagnostics="$(mktemp "${TMPDIR:-/tmp}/ingest-bench-helm.XXXXXX")" || return
	trap 'rm -f "$diagnostics"' EXIT
	if status_json="$(helm --kube-context "$KUBE_CONTEXT" status "$release" \
		--namespace "$namespace" --output json 2>"$diagnostics")"; then
		cat "$diagnostics" >&2
		status="$(jq -er '.info.status | select(type == "string")' <<<"$status_json")" ||
			die "invalid Helm status for operator release $namespace/$release"
		case "$status" in
		pending-* | uninstalling)
			die "operator release $namespace/$release is $status. Inspect helm status and helm history, then finish or recover that operation before rerunning setup."
			;;
		esac
	else
		cat "$diagnostics" >&2
		if ! grep -q 'release: not found' "$diagnostics"; then
			die "could not inspect operator release $namespace/$release"
		fi
	fi
)

install_spark_operator() {
	check_operator_release "$SPARK_OPERATOR_RELEASE" "$SPARK_OPERATOR_NAMESPACE"
	log "reconciling the Kubeflow spark-operator $SPARK_OPERATOR_VERSION"
	helm repo add "$SPARK_OPERATOR_RELEASE" "$SPARK_OPERATOR_REPO" --force-update
	# Use the benchmark service account bound to Pod Identity. The webhook adds
	# the ConfigMap volume mounts needed at /opt/bench/run.
	helm --kube-context "$KUBE_CONTEXT" upgrade --install "$SPARK_OPERATOR_RELEASE" \
		"$SPARK_OPERATOR_RELEASE/spark-operator" \
		--namespace "$SPARK_OPERATOR_NAMESPACE" --create-namespace \
		--version "$SPARK_OPERATOR_VERSION" \
		--set "spark.jobNamespaces={$NAMESPACE}" \
		--set spark.serviceAccount.create=false \
		--set spark.rbac.create=false \
		--set webhook.enable=true \
		--wait

	# Record the reconciled chart version.
	if ! SPARK_OPERATOR_RELEASES="$(helm --kube-context "$KUBE_CONTEXT" list --namespace "$SPARK_OPERATOR_NAMESPACE" \
		--filter "^$SPARK_OPERATOR_RELEASE\$" --output json 2>&1)"; then
		die "helm could not list the releases on $KUBE_CONTEXT: $SPARK_OPERATOR_RELEASES"
	fi
	log "spark operator: $(jq -r '.[0].chart // "not a helm release on this cluster"' <<<"$SPARK_OPERATOR_RELEASES")"
}

remove_msk_security_group() {
	local MSK_SG_NAME MSK_SG_ID DELETE_ERROR
	MSK_SG_NAME="$MSK_NAME-msk"
	[[ -n $VPC_ID && $VPC_ID != null ]] ||
		die "cannot identify the VPC for $CLUSTER_NAME; set VPC_ID to its original VPC and rerun to remove the MSK security group safely"
	# Names and benchmark tags can repeat across VPCs.
	MSK_SG_ID="$(aws ec2 describe-security-groups \
		--filters "Name=vpc-id,Values=$VPC_ID" "Name=group-name,Values=$MSK_SG_NAME" "Name=tag:$TAG_KEY,Values=true" \
		--query 'SecurityGroups[0].GroupId' --output text)"
	if [[ -n $MSK_SG_ID && $MSK_SG_ID != None ]]; then
		log "deleting security group $MSK_SG_NAME ($MSK_SG_ID)"
		if ! DELETE_ERROR="$(aws ec2 delete-security-group --group-id "$MSK_SG_ID" 2>&1)"; then
			case "$DELETE_ERROR" in
			*DependencyViolation*)
				die "$MSK_SG_ID is still in use: $DELETE_ERROR
	     MSK may retain network interfaces for a few minutes after cluster deletion. Wait, then rerun this script."
				;;
			*) die "could not delete $MSK_SG_ID: $DELETE_ERROR" ;;
			esac
		fi
	else
		log "security group $MSK_SG_NAME is already gone"
	fi
}
