# SPDX-License-Identifier: Apache-2.0
"""The headline table every published result is read through.

`collect` writes one document per run; this turns the whole `results/`
directory into the one page a reader compares them on. It reads nothing a
document does not already carry — no recomputation, no second source of truth
for a figure `collect` already derived — so the table can never disagree with
the documents it was built from, and regenerating it is always safe.

The render is a pure function of the documents given to it: same inputs, same
bytes, every time. That is what lets `validate-results.py` treat a stale
`RESULTS.md` as a publication failure rather than a judgement call.
"""

from __future__ import annotations

from pathlib import Path
from typing import cast

from ingest_bench.scorer.geometry import MIB
from ingest_bench.scorer.score import IDLE_STOP, PRODUCER_BOUND, VOID

_HEADER_ROW = (
    "| Engine | Variant | Preset | Date | Fleet | Validity | Freshness p50/p95/max (s) "
    "| Exactness | Keep-up | Cost ($/h) | File size p50 (MiB) |"
)
_SEPARATOR_ROW = "|---|---|---|---|---|---|---|---|---|---|---|"

_FOOTER = (
    "_Generated by `results-table` from the files under this directory. "
    "Never edit this file by hand — regenerate it instead._"
)

_NA = "n/a"


def _validity_cell(summary: dict[str, object]) -> str:
    """`valid`, or the reason a result is not: the same four words the
    publication rules use, so a reader never has to cross-reference `state`.
    """
    if cast(bool, summary["run_valid"]):
        return "valid"
    state = summary["state"]
    if state == PRODUCER_BOUND:
        return "producer_bound"
    if state == VOID:
        return "void"
    if state == IDLE_STOP:
        # An engine that went idle before the offer drained did not keep up
        # with what it was given — the fleet, not the offer, was short.
        return "undersized"
    return "not drained"


def _fleet_cell(fleet: list[dict[str, object]]) -> str:
    return " + ".join(f"{role['role']}×{role['count']} {role['machine_type']}" for role in fleet)


def _fmt(value: object, digits: int) -> str:
    return _NA if value is None else f"{cast(float, value):.{digits}f}"


def _freshness_cell(freshness: dict[str, object] | None) -> str:
    if freshness is None:
        return _NA
    window = cast(dict[str, object], freshness["window"])
    return f"{_fmt(window['p50_s'], 1)}/{_fmt(window['p95_s'], 1)}/{_fmt(window['max_s'], 1)}"


def _exactness_cell(exactness: dict[str, object] | None) -> str:
    if exactness is None:
        return _NA
    if cast(bool, exactness["exact"]):
        return "exact"
    return f"lost {exactness['loss_rows']} / dup {exactness['duplicate_rows']}"


def _keepup_cell(keepup: dict[str, object] | None) -> str:
    if keepup is None:
        return _NA
    absorbed = keepup["absorbed_at_offer_end"]
    pct = _NA if absorbed is None else f"{cast(float, absorbed) * 100:.1f}%"
    return f"{pct} / {_fmt(keepup['drain_s'], 1)}s"


def _cost_cell(run: dict[str, object], cost: dict[str, object]) -> str:
    """`n/a` when the site never disclosed real prices, rather than a $0.00 that
    reads as a free fleet.
    """
    pricing = cast(dict[str, object], run["site_pricing"])
    if pricing["vcpu_hour_usd"] == 0 and pricing["gib_hour_usd"] == 0:
        return _NA
    return _fmt(cost["usd_per_hour"], 2)


def _file_size_cell(geometry: dict[str, object] | None) -> str:
    if geometry is None:
        return _NA
    final = geometry["final"]
    if final is None:
        return _NA
    live = cast(dict[str, object], cast(dict[str, object], final)["live"])
    quantiles = cast(dict[str, object], live["size_quantiles"])
    p50 = quantiles["p50"]
    return _NA if p50 is None else f"{cast(float, p50) / MIB:.1f}"


def _row(document: dict[str, object]) -> tuple[tuple[str, str, str, str], str]:
    """One row, paired with the key it sorts by (preset, engine, variant, date)."""
    run = cast(dict[str, object], document["run"])
    spec = cast(dict[str, object], run["spec"])
    data = cast(dict[str, object], document["data"])
    summary = cast(dict[str, object], data["summary"])
    derived = cast(dict[str, object], document["derived"])

    engine = str(run["engine"])
    variant = str(run["variant"])
    preset = str(spec["corpus"])
    date = str(document["collected_at"])[:10]

    cells = (
        engine,
        variant,
        preset,
        date,
        _fleet_cell(cast(list[dict[str, object]], run["fleet"])),
        _validity_cell(summary),
        _freshness_cell(cast("dict[str, object] | None", derived["freshness"])),
        _exactness_cell(cast("dict[str, object] | None", derived["exactness"])),
        _keepup_cell(cast("dict[str, object] | None", derived["keepup"])),
        _cost_cell(run, cast(dict[str, object], derived["cost"])),
        _file_size_cell(cast("dict[str, object] | None", document["geometry"])),
    )
    return (preset, engine, variant, date), "| " + " | ".join(cells) + " |"


def render_results_table(documents: list[tuple[Path, dict[str, object]]]) -> str:
    """The Markdown page `results/RESULTS.md` is generated as.

    Every field is read straight out of a `run.json`; a document too broken to
    read (a required field absent) fails loudly with the path that broke,
    since a table that quietly drops a bad row would look like a clean run of
    `results-table` when it is really a document that never should have
    reached `results/` unvalidated.
    """
    rows: list[tuple[tuple[str, str, str, str], str]] = []
    for path, document in documents:
        try:
            rows.append(_row(document))
        except (KeyError, TypeError) as err:
            raise ValueError(f"{path}: does not hold the fields a results row needs: {err}") from err
    rows.sort(key=lambda entry: entry[0])

    versions = sorted({str(document["harness_version"]) for _, document in documents})
    harness_line = "Harness version(s): " + (", ".join(versions) if versions else "(none published yet)")

    lines = ["# Results", "", harness_line, "", _HEADER_ROW, _SEPARATOR_ROW]
    lines.extend(line for _, line in rows)
    lines.extend(["", _FOOTER])
    return "\n".join(lines) + "\n"
