# SPDX-License-Identifier: Apache-2.0
"""Render a comparison table from published run documents.

Read metrics from the documents without recomputing them. Rendering is
deterministic so validation can detect a stale ``RESULTS.md``.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from ingest_bench.collect.schema import (
    Cost,
    Exactness,
    FleetRole,
    Freshness,
    Geometry,
    Keepup,
    ResultDocument,
    Run,
    Summary,
    parse_result,
)
from ingest_bench.scorer.geometry import MIB
from ingest_bench.scorer.score import IDLE_STOP, PRODUCER_BOUND, VOID

_HEADER_ROW = (
    "| Engine | Variant | Preset | Date | Fleet | Validity | Freshness p50/p95/max (s) "
    "| Exactness | Keep-up | Cost ($/h) | File size p50 (MiB) |"
)
_SEPARATOR_ROW = "|---|---|---|---|---|---|---|---|---|---|---|"

_FOOTER = (
    "_Generated by `results-table` from the files under this directory. "
    "Never edit this file by hand — regenerate it instead._"
)

_NA = "n/a"


def _validity_cell(summary: Summary) -> str:
    """Return the validity label used in the results table."""
    if summary["run_valid"]:
        return "valid"
    state = summary["state"]
    if state == PRODUCER_BOUND:
        return "producer_bound"
    if state == VOID:
        return "void"
    if state == IDLE_STOP:
        # An undrained idle stop indicates insufficient ingest capacity.
        return "undersized"
    return "not drained"


def _fleet_cell(fleet: list[FleetRole]) -> str:
    return " + ".join(f"{role['role']}×{role['count']} {role['machine_type']}" for role in fleet)


def _fmt(value: float | None, digits: int) -> str:
    return _NA if value is None else f"{value:.{digits}f}"


def _freshness_cell(freshness: Freshness | None) -> str:
    if freshness is None:
        return _NA
    window = freshness["window"]
    return f"{_fmt(window['p50_s'], 1)}/{_fmt(window['p95_s'], 1)}/{_fmt(window['max_s'], 1)}"


def _exactness_cell(exactness: Exactness | None) -> str:
    if exactness is None:
        return _NA
    if exactness["exact"]:
        return "exact"
    return f"lost {exactness['loss_rows']} / dup {exactness['duplicate_rows']}"


def _keepup_cell(keepup: Keepup | None) -> str:
    if keepup is None:
        return _NA
    absorbed = keepup["absorbed_at_offer_end"]
    pct = _NA if absorbed is None else f"{absorbed * 100:.1f}%"
    return f"{pct} / {_fmt(keepup['drain_s'], 1)}s"


def _cost_cell(run: Run, cost: Cost) -> str:
    """Show ``n/a`` when prices are undisclosed, rather than implying a free fleet."""
    pricing = run["site_pricing"]
    if pricing["vcpu_hour_usd"] == 0 and pricing["gib_hour_usd"] == 0:
        return _NA
    return _fmt(cost["usd_per_hour"], 2)


def _file_size_cell(geometry: Geometry | None) -> str:
    if geometry is None:
        return _NA
    final = geometry["final"]
    if final is None:
        return _NA
    live = final["live"]
    quantiles = live["size_quantiles"]
    p50 = quantiles["p50"]
    return _NA if p50 is None else f"{p50 / MIB:.1f}"


def _row(document: ResultDocument) -> tuple[tuple[str, str, str, str], str]:
    """One row, paired with the key it sorts by (preset, engine, variant, date)."""
    run = document["run"]
    spec = run["spec"]
    data = document["data"]
    summary = data["summary"]
    derived = document["derived"]
    if summary is None:
        raise ValueError("data.summary: is null; a results row requires a scorer summary")

    engine = run["engine"]
    variant = run["variant"]
    preset = spec["corpus"]
    date = document["collected_at"][:10]

    cells = (
        engine,
        variant,
        preset,
        date,
        _fleet_cell(run["fleet"]),
        _validity_cell(summary),
        _freshness_cell(derived["freshness"]),
        _exactness_cell(derived["exactness"]),
        _keepup_cell(derived["keepup"]),
        _cost_cell(run, derived["cost"]),
        _file_size_cell(document["geometry"]),
    )
    return (preset, engine, variant, date), "| " + " | ".join(cells) + " |"


def render_results_table(documents: Sequence[tuple[Path, object]]) -> str:
    """Render ``results/RESULTS.md`` from run documents.

    Report malformed rows with their source paths instead of omitting them.
    """
    rows: list[tuple[tuple[str, str, str, str], str]] = []
    versions: set[str] = set()
    for path, document in documents:
        try:
            parsed = parse_result(document)
            rows.append(_row(parsed))
            versions.add(parsed["harness_version"])
        except ValueError as err:
            raise ValueError(f"{path}: does not hold the fields a results row needs: {err}") from err
    rows.sort(key=lambda entry: entry[0])

    harness_line = "Harness version(s): " + (", ".join(sorted(versions)) if versions else "(none published yet)")

    lines = ["# Results", "", harness_line, "", _HEADER_ROW, _SEPARATOR_ROW]
    lines.extend(line for _, line in rows)
    lines.extend(["", _FOOTER])
    return "\n".join(lines) + "\n"
